const runtimeRoot = process.env.PASPAS_RUNTIME_ROOT || '/var/www/paspas-runtime';
const current = `${runtimeRoot}/current`;

module.exports = {
  apps: [
    {
      name: 'paspas-api',
      cwd: `${current}/backend`,
      script: 'dist/index.js',
      interpreter: '/root/.bun/bin/bun',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      min_uptime: '20s',
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        HOST: '127.0.0.1',
        PORT: '8078',
      },
      out_file: '/root/.pm2/logs/paspas-api-out.log',
      error_file: '/root/.pm2/logs/paspas-api-error.log',
      combine_logs: true,
      time: true,
    },
    {
      name: 'paspas-panel',
      cwd: `${current}/admin`,
      script: 'server.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '450M',
      min_uptime: '20s',
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        HOSTNAME: '127.0.0.1',
        PORT: '3000',
        PANEL_API_URL: 'http://127.0.0.1:8078',
        NEXT_TELEMETRY_DISABLED: '1',
      },
      out_file: '/root/.pm2/logs/paspas-panel-out.log',
      error_file: '/root/.pm2/logs/paspas-panel-error.log',
      combine_logs: true,
      time: true,
    },
    {
      name: 'promats-frontend',
      cwd: `${current}/frontend-subpath`,
      script: 'server.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '450M',
      min_uptime: '20s',
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        HOSTNAME: '127.0.0.1',
        PORT: '3010',
        PROMATS_BASE_PATH: '/promats',
        NEXT_PUBLIC_BASE_PATH: '/promats',
        NEXT_TELEMETRY_DISABLED: '1',
      },
      out_file: '/root/.pm2/logs/promats-frontend-out.log',
      error_file: '/root/.pm2/logs/promats-frontend-error.log',
      combine_logs: true,
      time: true,
    },
    {
      name: 'promats-web',
      cwd: `${current}/frontend-root`,
      script: 'server.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '450M',
      min_uptime: '20s',
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        HOSTNAME: '127.0.0.1',
        PORT: '3012',
        API_BASE_URL: 'http://127.0.0.1:8078/api/web/promats',
        NEXT_TELEMETRY_DISABLED: '1',
      },
      out_file: '/root/.pm2/logs/promats-web-out.log',
      error_file: '/root/.pm2/logs/promats-web-error.log',
      combine_logs: true,
      time: true,
    },
  ],
};
