-- CRM V2/6: kanal bağımsız iletişim geçmişi.
CREATE TABLE IF NOT EXISTS `crm_communications` (
  `id` char(36) NOT NULL,
  `customer_id` char(36) NULL,
  `deal_id` char(36) NULL,
  `offer_id` char(36) NULL,
  `channel` varchar(24) NOT NULL,
  `direction` varchar(16) NOT NULL,
  `subject` varchar(255) NULL,
  `body` text NULL,
  `recipient` varchar(255) NULL,
  `status` varchar(24) NOT NULL DEFAULT 'logged',
  `provider_message_id` varchar(255) NULL,
  `error_message` varchar(1000) NULL,
  `occurred_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` char(36) NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_crm_comm_customer_time` (`customer_id`,`occurred_at`),
  KEY `idx_crm_comm_deal_time` (`deal_id`,`occurred_at`),
  KEY `idx_crm_comm_offer_time` (`offer_id`,`occurred_at`),
  CONSTRAINT `fk_crm_comm_customer` FOREIGN KEY (`customer_id`) REFERENCES `musteriler` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_crm_comm_deal` FOREIGN KEY (`deal_id`) REFERENCES `crm_deals` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_crm_comm_offer` FOREIGN KEY (`offer_id`) REFERENCES `teklifler` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_crm_comm_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_crm_comm_channel` CHECK (`channel` IN ('email','whatsapp','phone','manual')),
  CONSTRAINT `chk_crm_comm_direction` CHECK (`direction` IN ('incoming','outgoing')),
  CONSTRAINT `chk_crm_comm_status` CHECK (`status` IN ('logged','sent','failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
