import { randomUUID } from 'node:crypto';
import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import { pool } from '@/db/client';

type Row=RowDataPacket&Record<string,unknown>;
type ActivityBody={refType?:string|null;refId?:string|null;type?:string;subject?:string;body?:string|null;result?:string|null;nextActionAt?:string|null;durationMinutes?:number|null;plannedStartAt?:string|null;dueAt?:string|null;ownerUserId?:string|null;done?:boolean};
const refTables:Record<string,string>={musteri:'musteriler',talep:'teklif_talepleri',firsat:'crm_deals',teklif:'teklifler',siparis:'satis_siparisleri'};
const date=(value:string|null|undefined)=>value?new Date(value).toISOString().slice(0,19).replace('T',' '):value??null;

async function assertRef(type?:string|null,id?:string|null){if(!type&&!id)return;if(!type||!id||!refTables[type])throw new Error('gecersiz_aktivite_kaynagi');const [r]=await pool.execute<Row[]>(`SELECT id FROM ${refTables[type]} WHERE id=? LIMIT 1`,[id]);if(!r[0])throw new Error('aktivite_kaynagi_bulunamadi');}
export async function listActivities(q:{refType?:string;refId?:string;type?:string;done?:boolean;ownerUserId?:string;limit:number;offset:number}){const w=['1=1'];const v:unknown[]=[];for(const [c,x]of[['a.ref_type',q.refType],['a.ref_id',q.refId],['a.type',q.type],['a.owner_user_id',q.ownerUserId]]as const)if(x){w.push(`${c}=?`);v.push(x);}if(q.done!==undefined){w.push('a.done=?');v.push(q.done?1:0);}const from=`FROM crm_activities a LEFT JOIN users u ON u.id=a.owner_user_id WHERE ${w.join(' AND ')}`;const[items]=await pool.execute<Row[]>(`SELECT a.*,COALESCE(NULLIF(u.full_name,''),u.email) owner_name ${from} ORDER BY a.created_at DESC LIMIT ${q.limit} OFFSET ${q.offset}`,v);const[count]=await pool.execute<Row[]>(`SELECT COUNT(*) count ${from}`,v);return{items,total:Number(count[0]?.count??0)};}
export async function getActivity(id:string){const[r]=await pool.execute<Row[]>('SELECT * FROM crm_activities WHERE id=?',[id]);return r[0]??null;}
export async function createActivity(b:ActivityBody,userId:string|null){await assertRef(b.refType,b.refId);const id=randomUUID();await pool.execute(`INSERT INTO crm_activities(id,ref_type,ref_id,type,subject,body,result,next_action_at,duration_minutes,planned_start_at,due_at,owner_user_id,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,b.refType??null,b.refId??null,b.type,b.subject,b.body??null,b.result??null,date(b.nextActionAt),b.durationMinutes??null,date(b.plannedStartAt),date(b.dueAt),b.ownerUserId??userId,userId]);return getActivity(id);}
export async function updateActivity(id:string,b:ActivityBody){const current=await getActivity(id);if(!current)return null;const refType=b.refType===undefined?String(current.ref_type??'')||null:b.refType;const refId=b.refId===undefined?String(current.ref_id??'')||null:b.refId;await assertRef(refType,refId);const map:Record<string,unknown>={ref_type:b.refType,ref_id:b.refId,type:b.type,subject:b.subject,body:b.body,result:b.result,next_action_at:b.nextActionAt===undefined?undefined:date(b.nextActionAt),duration_minutes:b.durationMinutes,planned_start_at:b.plannedStartAt===undefined?undefined:date(b.plannedStartAt),due_at:b.dueAt===undefined?undefined:date(b.dueAt),owner_user_id:b.ownerUserId};if(b.done!==undefined){map.done=b.done?1:0;map.done_at=b.done?new Date():null;}const e=Object.entries(map).filter(([,x])=>x!==undefined);await pool.execute(`UPDATE crm_activities SET ${e.map(([k])=>`${k}=?`).join(',')} WHERE id=?`,[...e.map(([,x])=>x),id]);return getActivity(id);}
export async function deleteActivity(id:string){const[r]=await pool.execute<ResultSetHeader>('DELETE FROM crm_activities WHERE id=?',[id]);return r.affectedRows>0;}
export async function timeline(refType:string,refId:string){await assertRef(refType,refId);const[activities]=await pool.execute<Row[]>(`SELECT a.*,'activity' timeline_kind,COALESCE(a.done_at,a.planned_start_at,a.created_at) timeline_at,COALESCE(NULLIF(o.full_name,''),o.email) owner_name,COALESCE(NULLIF(c.full_name,''),c.email) created_by_name FROM crm_activities a LEFT JOIN users o ON o.id=a.owner_user_id LEFT JOIN users c ON c.id=a.created_by WHERE a.ref_type=? AND a.ref_id=?`,[refType,refId]);const column:{[key:string]:string|undefined}={musteri:'customer_id',firsat:'deal_id',teklif:'offer_id'};let communications:Row[]=[];if(column[refType]){const[rows]=await pool.execute<Row[]>(`SELECT c.*,'communication' timeline_kind,c.occurred_at timeline_at,COALESCE(NULLIF(u.full_name,''),u.email) created_by_name FROM crm_communications c LEFT JOIN users u ON u.id=c.created_by WHERE c.${column[refType]}=?`,[refId]);communications=rows;}return[...activities,...communications].sort((a,b)=>String(b.timeline_at).localeCompare(String(a.timeline_at))||String(b.id).localeCompare(String(a.id)));}
