import { randomUUID } from 'node:crypto';
import type { RowDataPacket } from 'mysql2';
import { pool } from '@/db/client';

type Row=RowDataPacket&Record<string,unknown>;
export type CommunicationBody={customerId?:string|null;dealId?:string|null;offerId?:string|null;channel:'email'|'whatsapp'|'phone'|'manual';direction:'incoming'|'outgoing';subject?:string|null;body?:string|null;recipient?:string|null;status?:'logged'|'sent'|'failed';providerMessageId?:string|null;errorMessage?:string|null;occurredAt?:string|null};
const date=(v:string|null|undefined)=>v?new Date(v).toISOString().slice(0,19).replace('T',' '):new Date().toISOString().slice(0,19).replace('T',' ');

async function resolveRefs(body:CommunicationBody){let customerId=body.customerId??null,dealId=body.dealId??null,offerId=body.offerId??null;if(dealId){const[r]=await pool.execute<Row[]>('SELECT musteri_id FROM crm_deals WHERE id=?',[dealId]);if(!r[0])throw new Error('firsat_bulunamadi');customerId=customerId??(String(r[0].musteri_id??'')||null);}if(offerId){const[r]=await pool.execute<Row[]>('SELECT t.musteri_id,dt.firsat_id FROM teklifler t LEFT JOIN crm_deal_teklifleri dt ON dt.teklif_id=t.id WHERE t.id=?',[offerId]);if(!r[0])throw new Error('teklif_bulunamadi');customerId=customerId??String(r[0].musteri_id);dealId=dealId??(r[0].firsat_id?String(r[0].firsat_id):null);}if(customerId){const[r]=await pool.execute<Row[]>('SELECT id FROM musteriler WHERE id=?',[customerId]);if(!r[0])throw new Error('musteri_bulunamadi');}return{customerId,dealId,offerId};}
export async function createCommunication(body:CommunicationBody,userId:string|null){const refs=await resolveRefs(body);const id=randomUUID();await pool.execute('INSERT INTO crm_communications(id,customer_id,deal_id,offer_id,channel,direction,subject,body,recipient,status,provider_message_id,error_message,occurred_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,refs.customerId,refs.dealId,refs.offerId,body.channel,body.direction,body.subject??null,body.body??null,body.recipient??null,body.status??'logged',body.providerMessageId??null,body.errorMessage??null,date(body.occurredAt),userId]);const[r]=await pool.execute<Row[]>('SELECT * FROM crm_communications WHERE id=?',[id]);return r[0];}
export async function listCommunications(q:{customerId?:string;dealId?:string;offerId?:string;channel?:string;limit:number;offset:number}){const w=['1=1'];const v:unknown[]=[];for(const[c,x]of[['customer_id',q.customerId],['deal_id',q.dealId],['offer_id',q.offerId],['channel',q.channel]]as const)if(x){w.push(`${c}=?`);v.push(x);}const from=`FROM crm_communications WHERE ${w.join(' AND ')}`;const[items]=await pool.execute<Row[]>(`SELECT * ${from} ORDER BY occurred_at DESC,id DESC LIMIT ${q.limit} OFFSET ${q.offset}`,v);const[count]=await pool.execute<Row[]>(`SELECT COUNT(*) count ${from}`,v);return{items,total:Number(count[0]?.count??0)};}
export async function recordOfferCommunication(offerId:string,channel:'email'|'whatsapp'|'manual',status:'sent'|'failed',recipient:string|null,userId:string|null,providerMessageId:string|null,errorMessage:string|null){return createCommunication({offerId,channel,direction:'outgoing',subject:'Teklif gönderimi',recipient,status,providerMessageId,errorMessage},userId);}
