import { randomUUID } from 'node:crypto';
import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import { pool } from '@/db/client';

type Row = RowDataPacket & Record<string, unknown>;
type ReminderBody = { sourceType:string; sourceId:string; remindAt:string; channel:'app'|'email'; title:string; message:string };
const sourceTables:Record<string,string>={activity:'crm_activities',deal:'crm_deals',offer:'teklifler',order:'satis_siparisleri'};
const sqlDate=(value:string)=>new Date(value).toISOString().slice(0,19).replace('T',' ');

async function assertSource(type:string,id:string){const table=sourceTables[type];if(!table)throw new Error('gecersiz_hatirlatma_kaynagi');const[rows]=await pool.execute<Row[]>(`SELECT id FROM ${table} WHERE id=? LIMIT 1`,[id]);if(!rows[0])throw new Error('hatirlatma_kaynagi_bulunamadi');}
export async function getReminder(id:string,userId:string){const[rows]=await pool.execute<Row[]>('SELECT * FROM crm_reminders WHERE id=? AND user_id=?',[id,userId]);return rows[0]??null;}
export async function createReminder(userId:string,body:ReminderBody,idempotencyKey:string=randomUUID()){await assertSource(body.sourceType,body.sourceId);const id=randomUUID();await pool.execute('INSERT IGNORE INTO crm_reminders(id,user_id,source_type,source_id,remind_at,channel,title,message,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?)',[id,userId,body.sourceType,body.sourceId,sqlDate(body.remindAt),body.channel,body.title,body.message,idempotencyKey]);const[rows]=await pool.execute<Row[]>('SELECT * FROM crm_reminders WHERE idempotency_key=?',[idempotencyKey]);return rows[0];}
export async function listReminders(userId:string,q:{status?:string;overdue?:boolean;limit:number;offset:number}){const where=['r.user_id=?'];const values:unknown[]=[userId];if(q.status){where.push('r.status=?');values.push(q.status);}if(q.overdue)where.push("r.status='pending' AND r.remind_at<NOW()");const from=`FROM crm_reminders r WHERE ${where.join(' AND ')}`;const[items]=await pool.execute<Row[]>(`SELECT r.* ${from} ORDER BY r.remind_at ASC LIMIT ${q.limit} OFFSET ${q.offset}`,values);const[count]=await pool.execute<Row[]>(`SELECT COUNT(*) count ${from}`,values);return{items,total:Number(count[0]?.count??0)};}
export async function cancelReminder(id:string,userId:string){const[result]=await pool.execute<ResultSetHeader>("UPDATE crm_reminders SET status='cancelled' WHERE id=? AND user_id=? AND status IN ('pending','failed')",[id,userId]);return result.affectedRows>0;}
export async function processDueReminders(userId?:string){const where=userId?' AND user_id=?':'';const[rows]=await pool.execute<Row[]>(`SELECT id FROM crm_reminders WHERE status='pending' AND remind_at<=NOW()${where} ORDER BY remind_at LIMIT 500`,userId?[userId]:[]);let sent=0,failed=0;for(const row of rows){const connection=await pool.getConnection();try{await connection.beginTransaction();const[claimed]=await connection.execute<ResultSetHeader>("UPDATE crm_reminders SET status='processing',error_message=NULL WHERE id=? AND status='pending'",[row.id]);if(!claimed.affectedRows){await connection.rollback();continue;}const[current]=await connection.execute<Row[]>('SELECT user_id,title,message,channel FROM crm_reminders WHERE id=? FOR UPDATE',[row.id]);const reminder=current[0];if(reminder.channel!=='app')throw new Error('email_hatirlatma_kanali_hazir_degil');await connection.execute('INSERT INTO notifications(id,user_id,title,message,type,is_read) VALUES(?,?,?,?,?,0)',[randomUUID(),reminder.user_id,reminder.title,reminder.message,'crm_reminder']);await connection.execute("UPDATE crm_reminders SET status='sent',sent_at=NOW() WHERE id=?",[row.id]);await connection.commit();sent++;}catch(error){await connection.rollback();await pool.execute("UPDATE crm_reminders SET status='failed',error_message=? WHERE id=? AND status='processing'",[(error instanceof Error?error.message:'hatirlatma_hatasi').slice(0,1000),row.id]);failed++;}finally{connection.release();}}return{selected:rows.length,sent,failed};}
export async function scheduleOfferFollowup(teklifId:string,userId:string){const[rows]=await pool.execute<Row[]>('SELECT t.teklif_no,m.ad musteri_ad FROM teklifler t JOIN musteriler m ON m.id=t.musteri_id WHERE t.id=?',[teklifId]);const offer=rows[0];if(!offer)return null;return createReminder(userId,{sourceType:'offer',sourceId:teklifId,remindAt:new Date(Date.now()+3*86400000).toISOString(),channel:'app',title:`Teklif takibi: ${offer.teklif_no}`,message:`${offer.musteri_ad??'Müşteri'} için gönderilen teklifin geri dönüşünü kontrol edin.`},`offer-followup:${teklifId}:${userId}`);}
export async function createStaleStageReminders(){const[rows]=await pool.execute<Row[]>(`SELECT d.id,d.owner_user_id,d.title,d.stage_id,d.updated_at,s.name stage_name FROM crm_deals d JOIN crm_stages s ON s.id=d.stage_id WHERE d.status='open' AND d.owner_user_id IS NOT NULL AND s.beklemede_uyari_gun IS NOT NULL AND TIMESTAMPDIFF(DAY,d.updated_at,NOW())>=s.beklemede_uyari_gun`);let created=0;for(const row of rows){const[result]=await pool.execute<ResultSetHeader>(`INSERT IGNORE INTO crm_reminders(id,user_id,source_type,source_id,remind_at,channel,title,message,idempotency_key) VALUES(?,?,?,?,NOW(),'app',?,?,?)`,[randomUUID(),row.owner_user_id,'deal',row.id,`Geciken fırsat: ${row.title}`,`${row.stage_name} aşamasındaki fırsat bekleme süresini aştı.`,`deal-stage-stale:${row.id}:${row.stage_id}:${String(row.updated_at).slice(0,10)}`]);created+=result.affectedRows;}return{matched:rows.length,created};}
