import type{RowDataPacket}from'mysql2';import{pool}from'@/db/client';
type Row=RowDataPacket&Record<string,unknown>;type Query={ownerUserId?:string;pipelineId?:string;source?:string;dateFrom?:string;dateTo?:string};
function filter(q:Query,alias='d'){const w=['1=1'];const v:unknown[]=[];if(q.ownerUserId){w.push(`${alias}.owner_user_id=?`);v.push(q.ownerUserId);}if(q.pipelineId){w.push(`${alias}.pipeline_id=?`);v.push(q.pipelineId);}if(q.source){w.push(`${alias}.source=?`);v.push(q.source);}if(q.dateFrom){w.push(`${alias}.created_at>=?`);v.push(`${q.dateFrom} 00:00:00`);}if(q.dateTo){w.push(`${alias}.created_at<DATE_ADD(?,INTERVAL 1 DAY)`);v.push(`${q.dateTo} 00:00:00`);}return{sql:w.join(' AND '),v};}
const nums=(rows:Row[])=>rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,typeof v==='string'&&/^-?\d+(\.\d+)?$/.test(v)?Number(v):v])));
export async function crmReports(q:Query){const f=filter(q);const offerFrom='FROM crm_deal_teklifleri dt JOIN crm_deals d ON d.id=dt.firsat_id JOIN teklifler t ON t.id=dt.teklif_id';const[stageFunnel,stageAging,userPerformance,sourcePerformance,offerRate,lossReasons,productSales,cycle]=await Promise.all([
pool.execute<Row[]>(`SELECT s.id stage_id,s.name stage_name,s.sort,COUNT(d.id) deal_count,COALESCE(SUM(d.amount),0) amount FROM crm_stages s LEFT JOIN crm_deals d ON d.stage_id=s.id AND ${f.sql} WHERE ${q.pipelineId?'s.pipeline_id=?':'1=1'} GROUP BY s.id,s.name,s.sort ORDER BY s.sort`,q.pipelineId?[...f.v,q.pipelineId]:f.v),
pool.execute<Row[]>(`SELECT s.id stage_id,s.name stage_name,COUNT(*) deal_count,ROUND(AVG(TIMESTAMPDIFF(HOUR,d.updated_at,NOW()))/24,2) current_stage_age_days,MAX(TIMESTAMPDIFF(DAY,d.updated_at,NOW())) max_stage_age_days FROM crm_deals d JOIN crm_stages s ON s.id=d.stage_id WHERE ${f.sql} AND d.status IN ('open','on_hold') GROUP BY s.id,s.name,s.sort ORDER BY s.sort`,f.v),
pool.execute<Row[]>(`SELECT d.owner_user_id,COALESCE(NULLIF(u.full_name,''),u.email,'Atanmamış') owner_name,COUNT(*) deal_count,SUM(d.status='won') won_count,SUM(d.status='lost') lost_count,ROUND(100*SUM(d.status='won')/NULLIF(SUM(d.status IN ('won','lost')),0),2) win_rate FROM crm_deals d LEFT JOIN users u ON u.id=d.owner_user_id WHERE ${f.sql} GROUP BY d.owner_user_id,owner_name ORDER BY won_count DESC,deal_count DESC`,f.v),
pool.execute<Row[]>(`SELECT COALESCE(d.source,'belirsiz') source,COUNT(*) deal_count,SUM(d.status='won') won_count,SUM(d.status='lost') lost_count,ROUND(100*SUM(d.status='won')/NULLIF(SUM(d.status IN ('won','lost')),0),2) win_rate FROM crm_deals d WHERE ${f.sql} GROUP BY d.source ORDER BY deal_count DESC`,f.v),
pool.execute<Row[]>(`SELECT COUNT(*) offer_count,SUM(t.gonderim_at IS NOT NULL) sent_count,SUM(t.durum='kabul') accepted_count,ROUND(100*SUM(t.durum='kabul')/NULLIF(SUM(t.gonderim_at IS NOT NULL),0),2) acceptance_rate ${offerFrom} WHERE ${f.sql}`,f.v),
pool.execute<Row[]>(`SELECT d.lost_reason_id,COALESCE(lr.name,d.lost_reason,'Belirsiz') reason,COUNT(*) lost_count FROM crm_deals d LEFT JOIN crm_loss_reasons lr ON lr.id=d.lost_reason_id WHERE ${f.sql} AND d.status='lost' GROUP BY d.lost_reason_id,reason ORDER BY lost_count DESC`,f.v),
pool.execute<Row[]>(`SELECT sk.urun_id,u.kod product_code,u.ad product_name,SUM(sk.miktar) quantity,SUM(sk.miktar*sk.birim_fiyat) revenue ${offerFrom} JOIN satis_siparisleri ss ON ss.id=t.donusen_siparis_id JOIN siparis_kalemleri sk ON sk.siparis_id=ss.id JOIN urunler u ON u.id=sk.urun_id WHERE ${f.sql} GROUP BY sk.urun_id,u.kod,u.ad ORDER BY revenue DESC`,f.v),
pool.execute<Row[]>(`SELECT COUNT(*) closed_count,ROUND(AVG(TIMESTAMPDIFF(HOUR,d.created_at,d.closed_at))/24,2) average_cycle_days,MIN(TIMESTAMPDIFF(DAY,d.created_at,d.closed_at)) min_cycle_days,MAX(TIMESTAMPDIFF(DAY,d.created_at,d.closed_at)) max_cycle_days FROM crm_deals d WHERE ${f.sql} AND d.status IN ('won','lost') AND d.closed_at IS NOT NULL`,f.v),
]);return{filters:q,funnel:nums(stageFunnel[0]),stageAging:nums(stageAging[0]),userPerformance:nums(userPerformance[0]),sourcePerformance:nums(sourcePerformance[0]),offerAcceptance:nums(offerRate[0])[0],lossReasons:nums(lossReasons[0]),productSales:nums(productSales[0]),salesCycle:nums(cycle[0])[0]};}
