import type { FastifyInstance } from 'fastify';
import { makeAdminPermissionGuard } from '@/common/middleware/permissions';
import { dealCreate, dealDelete, dealGet, dealMove, deals, dealUpdate, pipelines, talepConvert, products, productCreate, productUpdate, productDelete, needUpdate, dealToOffer } from './controller';
import { activities, activityCreate, activityDelete, activityGet, activityTimeline, activityUpdate } from './controller';
import { reminderCancel, reminderCreate, reminders, remindersGenerate, remindersProcess } from './controller';
import { communicationCreate, communications } from './controller';
import { lossReasonCreate, lossReasonDelete, lossReasons, lossReasonUpdate } from './controller';
import { automationEmit, automationRuleActive, automationRuleCreate, automationRules } from './controller';
import { dashboard } from './controller';
import { reports } from './controller';
import { savedViewCreate, savedViewDelete, savedViews, savedViewUpdate } from './controller';
import { requireOwnActivity, requireOwnDeal, requireOwnLead, requireOwnTimeline, requireScopedReference } from './scope';

export async function registerCrm(app: FastifyInstance) {
  const read = makeAdminPermissionGuard('admin.crm_firsatlar');
  const activity = makeAdminPermissionGuard('admin.crm_aktiviteler');
  const pipeline=makeAdminPermissionGuard('admin.crm_pipeline'),dashboardGuard=makeAdminPermissionGuard('admin.crm_dashboard'),reportsGuard=makeAdminPermissionGuard('admin.crm_raporlar'),automationGuard=makeAdminPermissionGuard('admin.crm_otomasyon'),leadGuard=makeAdminPermissionGuard('admin.crm_talepler');
  app.get('/crm/pipelines', { preHandler: read }, pipelines);
  app.get('/crm/firsatlar', { preHandler: read }, deals);
  app.post('/crm/firsatlar', { preHandler: read }, dealCreate);
  app.get('/crm/firsatlar/:id', { preHandler: [read,requireOwnDeal] }, dealGet);
  app.patch('/crm/firsatlar/:id', { preHandler: [read,requireOwnDeal] }, dealUpdate);
  app.delete('/crm/firsatlar/:id', { preHandler: [read,requireOwnDeal] }, dealDelete);
  app.patch('/crm/firsatlar/:id/asama', { preHandler: [read,requireOwnDeal] }, dealMove);
  app.get('/crm/firsatlar/:id/urunler', { preHandler: [read,requireOwnDeal] }, products);
  app.post('/crm/firsatlar/:id/urunler', { preHandler: [read,requireOwnDeal] }, productCreate);
  app.patch('/crm/firsatlar/:id/urunler/:productId', { preHandler: [read,requireOwnDeal] }, productUpdate);
  app.delete('/crm/firsatlar/:id/urunler/:productId', { preHandler: [read,requireOwnDeal] }, productDelete);
  app.put('/crm/firsatlar/:id/ihtiyac', { preHandler: [read,requireOwnDeal] }, needUpdate);
  app.post('/crm/firsatlar/:id/teklif-olustur', { preHandler: [read,requireOwnDeal] }, dealToOffer);
  app.post('/crm/talepler/:id/firsata-donustur', { preHandler: [leadGuard,requireOwnLead] }, talepConvert);
  app.get('/crm/aktiviteler', { preHandler: activity }, activities);
  app.post('/crm/aktiviteler', { preHandler: [activity,requireScopedReference] }, activityCreate);
  app.get('/crm/aktiviteler/:id', { preHandler: [activity,requireOwnActivity] }, activityGet);
  app.patch('/crm/aktiviteler/:id', { preHandler: [activity,requireOwnActivity] }, activityUpdate);
  app.delete('/crm/aktiviteler/:id', { preHandler: [activity,requireOwnActivity] }, activityDelete);
  app.get('/crm/zaman-cizelgesi/:refType/:refId', { preHandler: [activity,requireOwnTimeline] }, activityTimeline);
  app.get('/crm/hatirlatmalar', { preHandler: activity }, reminders);
  app.post('/crm/hatirlatmalar', { preHandler: activity }, reminderCreate);
  app.post('/crm/hatirlatmalar/isle', { preHandler: activity }, remindersProcess);
  app.post('/crm/hatirlatmalar/otomatik-uret', { preHandler: activity }, remindersGenerate);
  app.delete('/crm/hatirlatmalar/:id', { preHandler: activity }, reminderCancel);
  app.get('/crm/iletisimler', { preHandler: activity }, communications);
  app.post('/crm/iletisimler', { preHandler: [activity,requireScopedReference] }, communicationCreate);
  app.get('/crm/kaybetme-nedenleri', { preHandler: read }, lossReasons);
  app.post('/crm/kaybetme-nedenleri', { preHandler: pipeline }, lossReasonCreate);
  app.patch('/crm/kaybetme-nedenleri/:id', { preHandler: pipeline }, lossReasonUpdate);
  app.delete('/crm/kaybetme-nedenleri/:id', { preHandler: pipeline }, lossReasonDelete);
  app.get('/crm/otomasyonlar', { preHandler: automationGuard }, automationRules);
  app.post('/crm/otomasyonlar', { preHandler: automationGuard }, automationRuleCreate);
  app.patch('/crm/otomasyonlar/:id/aktif', { preHandler: automationGuard }, automationRuleActive);
  app.post('/crm/otomasyonlar/olay', { preHandler: automationGuard }, automationEmit);
  app.get('/crm/dashboard', { preHandler: dashboardGuard }, dashboard);
  app.get('/crm/raporlar', { preHandler: reportsGuard }, reports);
  app.get('/crm/gorunumler', { preHandler: read }, savedViews);
  app.post('/crm/gorunumler', { preHandler: read }, savedViewCreate);
  app.patch('/crm/gorunumler/:id', { preHandler: read }, savedViewUpdate);
  app.delete('/crm/gorunumler/:id', { preHandler: read }, savedViewDelete);
}
