import type{FastifyReply,FastifyRequest}from'fastify';import type{RowDataPacket}from'mysql2';import{pool}from'@/db/client';
type Row=RowDataPacket&Record<string,unknown>;type User={sub?:string;id?:string;role?:string;roles?:string[];is_admin?:boolean};
export function crmScope(req:FastifyRequest){const u=((req as{user?:User}).user??{}),roles=new Set([u.role,...(u.roles??[])]);return{userId:u.sub??u.id??null,isTeam:u.is_admin===true||roles.has('admin')};}
export async function requireOwnDeal(req:FastifyRequest,reply:FastifyReply){const s=crmScope(req);if(s.isTeam)return;if(!s.userId)return reply.code(403).send({error:{message:'forbidden'}});const id=(req.params as{id?:string}).id;if(!id)return;const[r]=await pool.execute<Row[]>('SELECT id FROM crm_deals WHERE id=? AND owner_user_id=?',[id,s.userId]);if(!r[0])return reply.code(403).send({error:{message:'forbidden'}});}
export async function requireOwnActivity(req:FastifyRequest,reply:FastifyReply){const s=crmScope(req);if(s.isTeam)return;if(!s.userId)return reply.code(403).send({error:{message:'forbidden'}});const id=(req.params as{id?:string}).id;if(!id)return;const[r]=await pool.execute<Row[]>('SELECT id FROM crm_activities WHERE id=? AND owner_user_id=?',[id,s.userId]);if(!r[0])return reply.code(403).send({error:{message:'forbidden'}});}
export async function requireOwnTimeline(req:FastifyRequest,reply:FastifyReply){const s=crmScope(req);if(s.isTeam)return;if(!s.userId)return reply.code(403).send({error:{message:'forbidden'}});const{refType,refId}=req.params as{refType:string;refId:string};let sql:string,values:unknown[];if(refType==='firsat'){sql='SELECT id FROM crm_deals WHERE id=? AND owner_user_id=?';values=[refId,s.userId];}else if(refType==='teklif'){sql='SELECT t.id FROM teklifler t LEFT JOIN crm_deal_teklifleri dt ON dt.teklif_id=t.id LEFT JOIN crm_deals d ON d.id=dt.firsat_id WHERE t.id=? AND (d.owner_user_id=? OR (d.id IS NULL AND t.created_by=?))';values=[refId,s.userId,s.userId];}else if(refType==='musteri'){sql='SELECT id FROM crm_deals WHERE musteri_id=? AND owner_user_id=? LIMIT 1';values=[refId,s.userId];}else{return reply.code(403).send({error:{message:'forbidden'}});}const[r]=await pool.execute<Row[]>(sql,values);if(!r[0])return reply.code(403).send({error:{message:'forbidden'}});}
export async function requireOwnLead(req:FastifyRequest,reply:FastifyReply){const s=crmScope(req);if(s.isTeam)return;if(!s.userId)return reply.code(403).send({error:{message:'forbidden'}});const id=(req.params as{id?:string}).id;if(!id)return;const[r]=await pool.execute<Row[]>('SELECT id FROM teklif_talepleri WHERE id=? AND atanan_user_id=?',[id,s.userId]);if(!r[0])return reply.code(403).send({error:{message:'forbidden'}});}
export async function requireOwnOffer(req:FastifyRequest,reply:FastifyReply){const s=crmScope(req);if(s.isTeam)return;if(!s.userId)return reply.code(403).send({error:{message:'forbidden'}});const id=(req.params as{id?:string}).id;if(!id)return;const[r]=await pool.execute<Row[]>('SELECT t.id FROM teklifler t LEFT JOIN crm_deal_teklifleri dt ON dt.teklif_id=t.id LEFT JOIN crm_deals d ON d.id=dt.firsat_id WHERE t.id=? AND (t.created_by=? OR d.owner_user_id=?)',[id,s.userId,s.userId]);if(!r[0])return reply.code(403).send({error:{message:'forbidden'}});}
export async function requireScopedReference(req:FastifyRequest,reply:FastifyReply){const s=crmScope(req);if(s.isTeam)return;if(!s.userId)return reply.code(403).send({error:{message:'forbidden'}});const b=req.body as{dealId?:string;customerId?:string;offerId?:string;refType?:string;refId?:string};let sql:string|undefined,values:unknown[]=[];if(b.dealId||(b.refType==='firsat'&&b.refId)){sql='SELECT id FROM crm_deals WHERE id=? AND owner_user_id=?';values=[b.dealId??b.refId,s.userId];}else if(b.offerId||(b.refType==='teklif'&&b.refId)){sql='SELECT t.id FROM teklifler t LEFT JOIN crm_deal_teklifleri dt ON dt.teklif_id=t.id LEFT JOIN crm_deals d ON d.id=dt.firsat_id WHERE t.id=? AND (t.created_by=? OR d.owner_user_id=?)';values=[b.offerId??b.refId,s.userId,s.userId];}else if(b.customerId||(b.refType==='musteri'&&b.refId)){sql='SELECT id FROM crm_deals WHERE musteri_id=? AND owner_user_id=? LIMIT 1';values=[b.customerId??b.refId,s.userId];}if(!sql)return;const[r]=await pool.execute<Row[]>(sql,values);if(!r[0])return reply.code(403).send({error:{message:'forbidden'}});}
