// RTK Query tag registry for the active MarketPulse admin surface.
export const tags = [
  'Auth',
  'User',
  'Profile',
  'AdminUsers',
  'UserRole',
  'UserRoles',
  'Role',
  'Roles',
  'Permissions',
  'Dashboard',
  'SiteSettings',
  'Storage',
  'Notification',
  'Notifications',
  'MenuItem',
  'AuditRequestLog',
  'AuditAuthEvent',
  'AuditMetric',
  'Settings',
  'MarketTarget',
  'MarketTargets',
  'MarketLead',
  'MarketLeads',
  'MarketSignal',
  'MarketSignals',
  'MarketStats',
  'LeadCandidates',
  'LeadMachineJobs',
  'AmazonRiskScores',
  'IcpProfiles',
  'LeadEnrichment',
  'OutreachDrafts',
  'MarketTestRuns',
  'MarketDeveloperNotes',
  'ScanRules',
  'SavedSearches',
] as const;

export type tag = typeof tags[number];
